name 'eb-supervisor'
version '0.0.1'
source 'git://github.com/mhahn/puppet-supervisor.git'
author 'Forked from plathrop'
license 'Apache'
summary 'Supervisor module'
description 'Supervisor module'
project_page 'http://github.com/mhahn/puppet-supervisor'
